name: Auto News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
      BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
      BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
      BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python auto_news_bot.py
Commit changes

Message: 🔧 Fix: Add env variables to GitHub Actions

Choose option: Commit directly to the main branch
