name: Run Auto News Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
      BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
      BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
      BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
      IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: python auto_news_bot.py
